"""empty message

Revision ID: 56d1409ee7ab
Revises: 90e144c6bd67
Create Date: 2019-12-02 13:34:41.326772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56d1409ee7ab'
down_revision = '90e144c6bd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('packages', 'date_to_deliver',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_unique_constraint(None, 'packages', ['date_created'])
    op.create_unique_constraint(None, 'packages', ['date_to_deliver'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packages', type_='unique')
    op.drop_constraint(None, 'packages', type_='unique')
    op.alter_column('packages', 'date_to_deliver',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
